### ISSUE TITLE
WindowsにVagrantをインストールしてCentOS7をインストールする

### ISSUE THREAD

**Issue by RVIRUS0817** [junwatanabe72/menta#1]
## やること

- windowsにVagrantをインストールする
- CentOS7をインストールし、linuxコマンドが打てるようになっていること
- yum updateを行う

## 参考

https://qiita.com/kenichi_nakamura/items/d714ad3051d8e1cc6f90

**Comment by junwatanabe72** [comment]
・vagrantとvirtualboxはインストール済。
・~/vagrant_centosというフォルダ作成。
・vagrant box add viniciusfs/centos7
・vagrant init viniciusfs/centos7
・vagrantfile編集
・vagrant up
・vagrant ssh
・sudo yum update

現在この状態です。
Complete!
[vagrant@localhost ~]$

**Comment by RVIRUS0817** [comment]
・vagrantとvirtualboxはインストール済。
・~/vagrant_centosというフォルダ作成。
- vagrant box add viniciusfs/centos7
- vagrant init viniciusfs/centos7
- vagrantfile編集
- vagrant up
- vagrant ssh
- sudo yum update

現在この状態です。
```
Complete!
[vagrant@localhost ~]$
```

@junwatanabe72 マークダウンはこんな感じで書いてもらえると見やすいです〜

**Comment by junwatanabe72** [comment]
#### 修正しました。お手すきの時にご確認ください。

1.vagrantとvirtualboxはインストール済だったので省略。
2.`mkdir vagrant_centos`でフォルダ作成
3.`vagrant box add viniciusfs/centos7`でcentos7をインストール
4.`vagrant init viniciusfs/centos7`でvagrantfileを作成
5.vagrantfileを編集

 ```
Vagrant.configure("2") do |config|
   config.vm.box = "viniciusfs/centos7"
   config.vm.network "private_network", ip: "192.168.33.10"
   config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
   end
end
```
6.`vagrant up`で起動
7.`vagrant ssh`で接続
8.`sudo yum update`
```
Complete!
[vagrant@localhost ~]$
```
