### ISSUE TITLE
Linux標準教科書を進める

### ISSUE THREAD

**Issue by RVIRUS0817** [junwatanabe72/menta#2]
## やってほしいこと

- Linux標準教科書を進めて、今日何を勉強したのか、わからないことをこのissuesに書いていく
https://linuc.org/textbooks/linux/

(例)
## 今日勉強したこと
- 
- 
- 

## わからなかったこと
- 
- 
-

**Comment by junwatanabe72** [comment]
2019/12/11　
## 今日勉強したこと
- Linuxとは（第一章）
  - OSの説明(ハードウェアとソフトウェアの違い、基本ソフトと応用ソフトの違い)
  - UNIXから続くLinux誕生と普及の歴史
  - Linuxディストリビューションの機能（パッケージやパッケージマネージャ機能）
-  Linuxの基本的なコマンド（第三章）
   - `ls`,`cp`,`pwd`,`mkdir`,`cat`,`which`,`man`,`more`,`less`,`find`
   -`(.)`,`(..)`,`(~)`,(/)`などのディレクトリ

私のcentos7環境にて、コマンドを実際に動かしましたが、正常に動作しました。
`find`,`cat`,`man`などのコマンドは知らなかったので勉強になりました。
今回は、理解できました。明日は第4章から進めます。

**Comment by junwatanabe72** [comment]
2019/12/12

## 今日勉強したこと
 - 正規表現とパイプ（第四章）
    - `>`,`|`,`grep`と正規表現
 - 基本的なコマンド２（第五章）
    - `touch`,`head`,`tail`,`sort`,`uniq`,`diff`,`tr`

今回もcentos7環境にて、実習しました。
未知のコマンドが多かったので、勉強になりました。
明日は、第6章から進めます。

**Comment by junwatanabe72** [comment]
2019/12/13

今日は急な予定が入ってしまい、勉強できませんでした。
明日は、第六章を進めます。

**Comment by junwatanabe72** [comment]
## 今日勉強したこと
- vi エディタ（第六章）
   - インサートモードやコマンドモードへの変更
   - `x`,`dd`,`yy`,`p`,`P`,`u`などのコマンド
   - `/文字列`,`n`の検索コマンド
   - `:ns/old/new/（オプション）`の置換コマンド 
- 管理者の仕事（第七章）
   - `useradd`,`usermod`,`userdel`のユーザーコマンド
   - `groupadd`,`groupmod`,`groupdel`のグループコマンド
   - `root`,`su`,`sudo`
 
今回もcentos7環境にて、実習しましたが、
今日は、vagrant 立ち上げで、なぜかエラーが発生し、
動かなくなってしまいました。
ログを消してしまったので、実際のログはありませんが、最下段に似たようなエラーです。
結局、centos7をアンインストールして、再度インストールしました。

再インストール方法
C:\Users\junwatanabe\.vagrant.d\boxes\ `viniciusfs-VAGRANTSLASH-centos7` を削除

`vagrantfiles` を削除
その後、再度、`centos7` を再度インストール

~~~
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
Command: ["modifyvm", "2bfc1a24-ce63-4996-9bf9-92dac90a7086", "--natpf1", "delete", "ssh"]
Stderr: VBoxManage.exe: error: The machine 'bpm857_default_1463030780543_14826' is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 462 of file VBoxManageModifyVM.cpp 
~~~

**Comment by junwatanabe72** [comment]
## 今日勉強したこと
- ユーザ権限とアクセス権（第八章）
  - ファイルの所有者と所有グループの概念
  - `chown`,`chgrp`コマンド
  - `rwx`と`chmod`や`umask`を使用した権限変更
  - `setuid`,`setgid`,`sticky`コマンド
- シェルスクリプト（第九章）
  - シェルとは、シェルスクリプトとは
  -  `echo`,`$`,`export環境変数`,`read`,`set`,`unset`,`env`コマンド
  - `"",``,''`の違い
  - `shift`,`\`,`source`
  - `if`,`case`,`for`,`while`,`until`,`select`,`function`,`sh`のスクリプト

今回もcentos7環境にて、実習しました。
Linuxでも、プログラミング言語のような文法があるってことが、新たな発見です。
一度では、すべて理解できそうにないので、繰り返し勉強していきます。
明日は、第10章から進めます。

**Comment by junwatanabe72** [comment]
## 今日勉強したこと

- ネットワークの設定と管理（第10章）
   -  TCP/IP、ローカルとワイド
   -   `ping`コマンドと接続確認
   -  IPアドレスのクラス（ネットワークアドレスとホストアドレス）
   -  CIDR表記
   - `traceroute`,`tracepath`でゲートウェイを調べる
   -  `ip a`,`nmcli`,`nmtui`IPアドレスの確認
   -  `ip route`,`add`,`del`のルーティング変更
   -  `nslookup`コマンドを使った名前確認
   -  `firewall`,`iptables`によるセキュリティ設定

## わからなかったこと
 - IPアドレス
    - IPアドレスの割振りには、クラス分けされたIPアドレスとCIDRの２パターンがあることは理解しました。これらは、現在、同時に運用されているのでしょうか。また、これからは、CIDRでの契約に一本化されていくということでしょうか。ちなみに、このような契約は、大手法人やプロバイダーがすることで個人では関係ないという理解でよろしいでしょうか。
   -`vi /etc/sysconfig/network-scripts/ifcfg-eth0`にて、IPアドレスを変更しましたが、勝手に変更しても問題ないのでしょうか（ネット接続できなくなりますよね？）。または、プライベートIPアドレスの範囲であれば、問題ないということでしょうか。
   - ‘IP route add`コマンドにて、ルーティングを変更しました。ルーティングを変更しても、外部接続するためのゲートウェイIPアドレスを変更していなれれば、問題なくネットワークの外へ接続できるということでしょうか。そうであれば、ルーティングでIPアドレスを変更することって意味あるのでしょうか。
- セキュリティ
   - `firewall -cmd --add-service=https`はhttpsの接続のみ有効という理解でよいですか。
   - `-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT `は、apacheサーバにhttpリクエストの受取許可を出したという理解でよいでしょうか。
- 章末テスト(自信がないところだけ)
  - (4)
~~~
[root@localhost vagrant]# ip route add 8.8.8.8 via 10.0.2.2 dev eth0

[root@localhost vagrant]# ip route
default via 10.0.2.2 dev eth0
default via 10.0.2.2 dev eth0 proto dhcp metric 100

8.8.8.8 via 10.0.2.2 dev eth0

10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 metric 100
169.254.0.0/16 dev eth0 scope link metric 1002
169.254.0.0/16 dev eth1 scope link metric 1003
192.168.33.0/24 dev eth1 proto kernel scope link src 192.168.33.10 
~~~

    -(5)
~~~
/etc/hosts.allow ALL : ALL
/etc/hosts.deny sshd : 192.168.100.20 
 ~~~

この１０章は、私にとっては、専門性が高く、かなり時間を要しました。
お手すきの時に、分からなかったことについて、ご確認いただければ
幸いです。
よろしくお願いいたします。

**Comment by junwatanabe72** [comment]
## 今日勉強したこと
  - 第１１章（プロセス管理）
     -  プロセス、スケジューリング、ジョブ（フォアグランド、バックグラウンド）
     -  プロセスID 、シグナルコマンド
     -  `top`,`pstree`によるプロセスの関係

## わからなかったこと
  -  プロセスとジョブの関係が、うまく理解できませんでした。プロセスが集まった複雑な作業のひと塊がjobという認識でよいでしょうか。

明日は１２章に取り組みたいと思います。

**Comment by junwatanabe72** [comment]
## 今日勉強したこと
 - 第１２章（ファイル管理）
   -  ハードディスク利用方法(sdbのパーティションsdb1,sdb2の作成)
   - ファイルシステム（マウント処理、アンマウント処理）
   -  スワップ領域の有効化、無効化
   -  自動マウント、iノード番号とは、DVDROMマウント
   -  ハードリンクとシンボリックリンク
   -  ディスク管理（`fsck`コマンドと`du`コマンド）

- 章末テスト
(1)   ハードディスクを確認できるコマンドは

`fdisk -l`

(2)  スワップファイルシステムとは

カーネルプログラムがデータを読み込む際に、メモリ領域を使用するが、
メモリ領域が不足した場合に、今使用していないメモリ領域上のプログラムや
データを一時的に退避できるよう、
ハードディスクのパーティションをスワップ領域として確保したシステムのこと

(3)ext3やext4がext2より優れている点を１つ

ファイルシステムに対する書き換え処理コマンドをファイルシステムに記録するジャーナリング機能が実装されている点

(4)ハードリンクとシンボリックリンクの違い

- ハードリンク
  - iノード番号やファイルの実体を共有している。
  - 元ファイルを消しても、アクセスが可能。
  - 別ファイルシステムには作成負荷。
- シンボリックリンク
  - パスを示す疑似的なファイル。
  - 元ファイルを消した場合、アクセスエラーとなる
  -  別ファイルシステムでも使用可能

(5)ログインユーザのホームディレクトリ使用量の表示コマンド

`du -s /home/ユーザー名`

わかったようなわかってないような状況です。
何度も勉強する必要があるなと感じています。
章末テストが不安なので、回答を掲載します。
お手すきの際にご確認ください。

完璧には理解できていないかもしれませんが、
標準教科書を最後まで読み進めました。

**Comment by RVIRUS0817** [comment]
```
IPアドレス
IPアドレスの割振りには、クラス分けされたIPアドレスとCIDRの２パターンがあることは理解しました。これらは、現在、同時に運用されているのでしょうか。また、これからは、CIDRでの契約に一本化されていくということでしょうか。ちなみに、このような契約は、大手法人やプロバイダーがすることで個人では関係ないという理解でよろしいでしょうか。

-vi /etc/sysconfig/network-scripts/ifcfg-eth0にて、IPアドレスを変更しましたが、勝手に変更しても問題ないのでしょうか（ネット接続できなくなりますよね？）。または、プライベートIPアドレスの範囲であれば、問題ないということでしょうか。

‘IP route add`コマンドにて、ルーティングを変更しました。ルーティングを変更しても、外部接続するためのゲートウェイIPアドレスを変更していなれれば、問題なくネットワークの外へ接続できるということでしょうか。そうであれば、ルーティングでIPアドレスを変更することって意味あるのでしょうか。

セキュリティ
firewall -cmd --add-service=httpsはhttpsの接続のみ有効という理解でよいですか。
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT は、apacheサーバにhttpリクエストの受取許可を出したという理解でよいでしょうか。
```

> IPアドレスとCIDRですが、そもそもCIDR表記と言ってIPアドレスとサブネットマスクを両方一度に書きたい場合に必要となります。なのでawsなどは基本CIDR表記なので覚えておくといいかと。なので将来一本化されるということはありません。

> /etc/sysconfig/network-scripts/ifcfg-eth0ですが基本的にローカルIPを変更する部分なので、用途に合わせて変更する機能です。

> ルーティングでIPアドレスを変更することって意味あるのでしょうか。
オンプレミスの場合ルーティングをしないとネットワークが繋がりません。
なので必要となります。

>firewall -cmd --add-service=httpsはhttpsの接続のみ有効という理解でよいですか。
↑そのとおりです。
https://qiita.com/kenjjiijjii/items/1057af2dddc34022b09e こちら参考に。
