### ISSUE TITLE
ログ修正を行う

### ISSUE THREAD

**Issue by RVIRUS0817** [junwatanabe72/menta#4]
## 要件

以下のように100行あるファイルがある。
下記のように正規表現で自動的に変更してほしい。

[test.log](https://github.com/junwatanabe72/menta/files/3999181/test.log)

```
INSERT INTO menta_user (user_id, login_date) VALUES (00, '2019-12-25 18:31:38');
INSERT INTO menta_user (user_id, login_date) VALUES (00, '2019-12-25 18:31:38');
INSERT INTO menta_user (user_id, login_date) VALUES (00, '2019-12-25 18:31:38');
INSERT INTO menta_user (user_id, login_date) VALUES (00, '2019-12-25 18:31:38');
x 100
```

**Comment by junwatanabe72** [comment]
変換完了しました。

課題のプロセス
- シェルスクリプトの作成
  -  test.logから、`00`,`2019-12-25 18:31:38`を`sed`コマンドにて取得。
  -  for文を使用するため、`sed`で取得した値を配列に変換。 
  -  値を配列にし、for文にて、`INSERT INTO文`に挿入。

- 上手くいかなかったこと
  - 配列を上手く、`INSERT INTO文`に挿入できませんでした。
`00`と`2019-12-25 18:31:38`で値を取得し、`INSERT INTO文`に挿入したところ、
`2019-12-25 18:31:38`が`2019-12-25`と`18:31:38`に分離。
苦肉の策で、値を三つに分けて取得（`00`,`2019-12-25`,`18:31:38`）、
結果、VALUES (`00`, `'2019-12-25 18:31:38'`);→VALUES (`00`, `2019-12-25` `18:31:38`);
としました。
  -  そもそも冗長なコードになってしまったので、シンプルにかけるのであれば、ご教授いただきたいです。

シェルスクリプト（exchange.sh）
~~~
#!/bin/bash

aa=$(sed -e "s/\(^[0-9]\{2\}\)[ \f\n\r\t]\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}[ \f\n\r\t][0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}$\)/\1/" ./test.log)
bb=$(sed -e "s/\(^[0-9]\{2\}\)[ \f\n\r\t]\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}[ \f\n\r\t]\)\([0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}$\)/\2/" ./test.log)
cc=$(sed -e "s/\(^[0-9]\{2\}\)[ \f\n\r\t]\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}[ \f\n\r\t]\)\([0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}$\)/\3/" ./test.log)

array=($aa)
brray=($bb)
crray=($cc)

for ix in ${!array[@]}
do
echo "INSERT INTO menta_user (user_id, login_date) VALUES (${array[ix]}, '${brray[ix]} ${crray[ix]}');"
done
~
~~~

**Comment by RVIRUS0817** [comment]
@junwatanabe72 
おーシェルスクリプトでやったんですね。
ちなみにvimの正規表現のほうが楽だと思いますよ。
https://qiita.com/waoooon/items/8d982e49692c8145ca4b
